pipeline:
  backend:
    image: node
    commands:
      - npm install
      - npm test
      - npm run pack
  terraform:
    image: jmccann/drone-terraform:1
    plan: false
    root_dir: infrastructure
