pipeline:
  build:
    image: node
    commands:
      - echo $$github_token
      - npm install
      - npm test
      - npm run pack
  publish:
    image: plugins/npm
    registry: https://npm.pkg.github.com/swamikalagiri
    token: $GITHUB_TOKEN
    
  deploy:
    image: jmccann/drone-terraform:1
    plan: false
    root_dir: infrastructure
