kind: pipeline
name: default

steps:
  - name: build
    image: node
    commands:
      - npm install
      - npm test
#       - npm run pack
#   - name: publish
#     image: plugins/npm
#     settings:
#       registry: https://npm.pkg.github.com/swamikalagiri
#       username: swamikalagiri
#       password: 
#         from_secret: github_token
#       email: swami.kalagiri@gmail.com
  - name: terraform
    image: jmccann/drone-terraform:5
    pull: always
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    settings:
      tf_version: 1.0.0
      root_dir: infrastructure/
      actions:
        - validate
        - plan
        - apply
